### ISSUE TITLE
Add logos to sign in buttons

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/automate#26]
Most "sign in with..." buttons include the logo of the company or service users will sign in with. To improve the user experience with the application, add the logos for Microsoft and GitHub to their respective sign-in buttons.

**Comment by rohinimohan14** [comment]
Hi ! I'd like to work on this issue. Do I add the Logo first followed by the text?

**Comment by tacosontitan** [comment]
@rohinimohan14 the industry seems to have it standardized to the left, so let's go to the left.
