### ISSUE TITLE
Add color palette to CSS

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/automate#5]
# Base Color Palette
![image](https://user-images.githubusercontent.com/65432314/152179872-5a2b6c8d-867c-48d5-99b3-375668d3b2b5.png)

The color palette in the image above is the current base color palette for _automate_. The global CSS file needs to have variables defined for these base colors by name:

- Gunmetal: `1d252f`
- Corn: `fff36e`
- Cedar Chest: `db504a`
- Ocean Green: `48bf84`
- Carolina Blue: `00a8e8`

Additionally, there should be classes that use these colors for text and backgrounds, for example:

```css
.text-corn { ... }
.background-corn { ... }
```
<sub>***NOTE**: Gunmetal is the only color that should **NOT** have a text class.*</sub>

# Highlight Color Palette
![image](https://user-images.githubusercontent.com/65432314/152182787-13505aaa-2dc8-45bc-bfa1-471e9bde0a0a.png)

The highlight color palette will need to be implemented as variable definitions until control classes are implemented, at which point their hover classes will utilize the variables.

- Charcoal: `3e4759`
- Green Yellow Crayola: `f8e98f`
- Candy Pink: `db716d`
- Pale Ocean Green: `76bd96`
- Cyan Process: `36aae0`

**Comment by whoamihealay** [comment]
Hi, I can take this issue! Can you point me to the Global CSS file? Is it main.css or loader.css?

**Comment by tacosontitan** [comment]
> Hi, I can take this issue! Can you point me to the Global CSS file? Is it main.css or loader.css?

@whoamihealay it's the `main.css` file; sorry for the lack of clarity, and thank you for helping out!
